### ISSUE TITLE
想请教下作者关于模型训练于推理的问题

### ISSUE THREAD

**Issue by Jasonx0123** [RewindL/Self-ShadowGAN#1]
请问下作者应该如何利用main.py进行训练呢？main.py在推理时是不需要权重文件吗？

**Comment by RewindL** [comment]
你好。
- Self-ShadownGAN是一个针对单张图像训练的模型，因此对于每一张输入阴影图像，需要初始化网络参数进行即时训练（和Deep Image Prior/SinGAN相同），训练结束后网络的推理结果即为去阴影结果。你也可以根据自己的需要使用自定义的网络进行训练。
- 我们在Readme中提供了参考的训练代码，其中参数--idx为./images文件夹下的图片索引。（如设置为1，则读取./images/Shadows/1.png作为阴影输入）
- 由于对于每一张阴影图像我们都需要单独训练网络，因此我们没有提供预训练权重，但我们提供了16组测试样例。你也可以修改mian.py中的对应代码将自己的阴影图片作为训练输入。

**Comment by Jasonx0123** [comment]
好的，明白了，谢谢作者
