### ISSUE TITLE
请教下作者请问关于代码的问题

### ISSUE THREAD

**Issue by Jasonx0123** [RewindL/Self-ShadowGAN#2]
想请教下作者，论文中提到的启发于“Shadow Removal via Shadow Image Decomposition”和 “ From Shadow Segmentation to Shadow Removal”，我只找到了第一篇论文的开源代码，第二篇的代码原作者没开源，想请问下作者有其他可以参考的论文代码吗？

**Comment by RewindL** [comment]
你好。“From Shadow Segmentation to Shadow Removal”(SS)这篇论文和“Shadow Removal via Shadow Image Decomposition”(SID)的线性去阴影模型是一样的，区别在于SS把训练数据转化成了非成对的patches，loss也变为了gan loss。所以你可以基于SID的源码作相应的修改。

**Comment by Jasonx0123** [comment]
好的谢谢，请问把训练数据转化成了非成对的patches有可以参考的代码吗？

**Comment by RewindL** [comment]
> 好的谢谢，请问把训练数据转化成了非成对的patches有可以参考的代码吗？

作者没有提供所有的细节，所以只能结合自己的理解复现了。至于怎么把img转为patch，你可以参考我们的Self-ShadowGAN的patch构造函数，或者移步搜索引擎看看别人的实现。

**Comment by Jasonx0123** [comment]
好的，谢谢

**Comment by Jasonx0123** [comment]
请教下作者，请问下在进行对比实验的时候，是通过循环训练测试集中的单张图片获得的结果吗？还是利用了另外的代码训练训练集，再加载权重对测试集测试获得的呢？




小熙
***@***.***
